<!doctype html>
<html lang="vi">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MOFI · Hiểu tiền, đầu tư tốt hơn</title>@viteReactRefresh @vite(['resources/css/app.css','resources/js/public.tsx'])</head>
<body class="mofi-body public-desktop">
<header class="site-nav">
    <a class="brand" href="/"><span class="brand-mark">M</span><span>MOFI<small>Hiểu tiền, đầu tư tốt hơn.</small></span></a>
    <nav aria-label="Điều hướng chính"><a href="/" class="selected">Trang chủ</a><a href="#features">Sản phẩm</a><a href="/learn">Học đầu tư</a><a href="/pricing">Bảng giá</a><a href="/community">Cộng đồng</a><a href="/about">Về MOFI</a></nav>
    <div class="nav-actions">@auth<a class="button button-blue" href="/dashboard">Vào dashboard →</a>@else<a class="nav-login" href="/login">Đăng nhập</a><a class="button button-blue" href="/register">Đăng ký miễn phí →</a>@endauth</div>
</header>
<main>
    <section class="hero"><div class="hero-copy"><p class="eyebrow">NỀN TẢNG TÀI CHÍNH CHO NGƯỜI VIỆT</p><h1>Hiểu tiền hôm nay,<br><em>vững tương lai mai sau</em></h1><p class="hero-lead">Quản lý tài sản, học đầu tư và thử chiến lược trong một không gian tài chính rõ ràng.</p><div class="hero-actions"><a class="button button-blue button-large" href="/register">Đăng ký miễn phí →</a><a class="button button-ghost button-large" href="#features">Khám phá MOFI</a></div><div class="trust-row"><span>✓ Tiền ảo để thực hành</span><span>✓ Không cần thẻ tín dụng</span><span>✓ Dữ liệu có nguồn</span></div></div><div id="product-preview" aria-label="Minh họa dashboard trên màn hình máy tính"></div></section>
    <section class="stats" aria-label="Khả năng bản demo"><div><b>4 nhóm tài sản</b><span>Cổ phiếu, chỉ số, vàng, tiền mã hóa</span></div><div><b>1 không gian</b><span>Tài sản, danh mục và mục tiêu</span></div><div><b>30 ngày</b><span>Lịch sử danh mục mô phỏng</span></div><div><b>3 bài học</b><span>Bắt đầu hành trình đầu tư</span></div></section>
    <div class="landing-sections">
        <section class="products-section" id="features"><div class="section-heading"><div><h2>Một nền tảng. Toàn bộ hành trình của bạn.</h2><p>Từ hiểu dòng tiền đến thử nghiệm chiến lược, từng bước chủ động hơn.</p></div><a href="/products">Khám phá sản phẩm →</a></div><div class="feature-grid" id="public-features"></div></section>
        <section class="public-intelligence"><article class="ai-band"><div><p class="eyebrow">MOFI COPILOT</p><h2>Hỏi MOFI.<br>Hiểu rõ dữ liệu của bạn.</h2><p>Tóm tắt danh mục, phân bổ tài sản và tiến độ mục tiêu từ chính số liệu của bạn.</p><a href="/copilot" class="ask-box">Danh mục của tôi đang thế nào? <b>→</b></a><div class="copilot-prompts"><a href="/copilot">Tỷ trọng tiền mặt</a><a href="/simulation">Nếu thị trường giảm 20%?</a><a href="/goals">Kế hoạch cho mục tiêu</a></div><small>Bản demo trả lời theo quy tắc, chưa kết nối mô hình AI.</small></div><div class="copilot-emblem" aria-hidden="true">M<span>MOFI</span></div></article><article class="panel public-market" id="public-market" aria-live="polite"></article></section>
        <section class="life-section"><img src="/images/journey.jpg" alt="Phong cảnh núi và hành trình khám phá" loading="lazy"><div><h2>Đầu tư không chỉ là con số,<br>mà là một cuộc sống tốt hơn.</h2><p>Một kế hoạch tốt bắt đầu từ điều quan trọng với bạn. Chọn đích đến, theo dõi tiến độ mỗi ngày.</p></div><div class="life-goals">@foreach(['Mua nhà','Học cho con','Nghỉ hưu','Mua xe','Quỹ dự phòng','Tự do tài chính'] as $goal)<a href="/goals"><span aria-hidden="true">{{ sprintf('%02d', $loop->iteration) }}</span>{{ $goal }}</a>@endforeach</div></section>
        <section class="public-bottom"><div><div class="section-heading"><h2>Mỗi người một hành trình</h2><span>Tình huống minh họa</span></div><div class="quote-grid"><article><span class="persona">01</span><h3>Người mới bắt đầu</h3><p>“Tôi muốn hiểu dòng tiền trước khi chọn khoản đầu tư đầu tiên.”</p><a href="/learn">Bắt đầu từ kiến thức →</a></article><article><span class="persona">02</span><h3>Người có kế hoạch</h3><p>“Tôi cần theo dõi quỹ dự phòng và mục tiêu mua nhà ở cùng một nơi.”</p><a href="/goals">Xây dựng mục tiêu →</a></article><article><span class="persona">03</span><h3>Người thích khám phá</h3><p>“Tôi muốn thử tác động của thị trường trước khi đưa ra quyết định.”</p><a href="/simulation">Khám phá mô phỏng →</a></article></div></div><aside class="join-card"><h2>Bắt đầu hành trình đầu tư cùng MOFI</h2><ul><li>✓ Theo dõi tài sản trực quan</li><li>✓ Giao dịch bằng tiền ảo</li><li>✓ Lưu mục tiêu và tiến độ học</li><li>✓ Không cần thẻ tín dụng</li></ul><a class="button button-blue" href="/register">Đăng ký miễn phí →</a></aside></section>
    </div>
</main>
<footer class="site-footer"><a class="brand" href="/"><span class="brand-mark">M</span><span>MOFI<small>Hiểu tiền, đầu tư tốt hơn.</small></span></a><a href="/about">Về MOFI</a><a href="/policies">Điều khoản & bảo mật</a><a href="/products">Sản phẩm</a><a href="/community">Cộng đồng</a><small>Đầu tư thông minh hơn. Mỗi ngày.</small></footer>
</body></html>
