import React, { useState, type ReactNode } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';

type Row = Record<string, any>;
const money = (v:any) => v === null || v === undefined ? 'Chưa đủ giá' : new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}).format(Number(v))+' ₫';
const number = (v:any) => new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(Number(v));
function Empty({children='Chưa có dữ liệu. Hãy thêm mục đầu tiên.'}:{children?:ReactNode}) {return <p className="empty-state">{children}</p>}

export function Sparkline({rows,positive}:{rows:Row[];positive:boolean}) {return <div className="sparkline" aria-label="Xu hướng giá 30 ngày"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={32}><AreaChart data={[...rows].reverse().map(r=>({value:Number(r.close)}))}><YAxis hide domain={['dataMin','dataMax']}/><Area dataKey="value" stroke={positive?'#18a77c':'#d44b5e'} fill={positive?'#e4f8ef':'#fff1f2'} strokeWidth={1.6} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>}

export function PortfolioChart({s}:{s:Row}) {const [days,setDays]=useState(30);return <><div className="chart-value"><strong>{money(s.portfolio_value)}</strong><span>Tiền mặt + chứng khoán · 30 ngày mô phỏng</span></div><div className="chart-ranges">{[7,14,30].map(d=><button key={d} className={days===d?'selected':''} onClick={()=>setDays(d)}>{d} ngày</button>)}</div><div className="actual-chart"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={180}><AreaChart data={s.history.slice(-days).map((r:Row)=>({...r,value:r.value===null?null:Number(r.value)}))} margin={{left:0,right:8,top:10,bottom:0}}><defs><linearGradient id="valueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#18a77c" stopOpacity={.3}/><stop offset="100%" stopColor="#18a77c" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7eff5"/><XAxis dataKey="date" tickFormatter={d=>d.slice(8,10)+'/'+d.slice(5,7)} minTickGap={30} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={['auto','auto']} tickFormatter={v=>number(v/1e6)+'tr'} width={48} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)} labelFormatter={d=>'Ngày '+d}/><Area name="Giá trị danh mục" type="monotone" dataKey="value" stroke="#16a87a" fill="url(#valueFill)" strokeWidth={2.5} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>{s.status!=='complete'&&<p className="form-error">Có tài sản thiếu giá. Biểu đồ giữ khoảng trống tại ngày chưa đủ dữ liệu.</p>}</>}

export function Allocation({s}:{s:Row}){const values=[['Chứng khoán',s.securities_value,'#397fcb'],['Tiền mặt',s.cash,'#24b987'],['Tài sản khác',s.manual_assets,'#f5bc3c']];return s.total_assets===null?<Empty>Chưa đủ giá để tính phân bổ tài sản.</Empty>:Number(s.total_assets)===0?<Empty>Chưa có tài sản. Nạp tiền ảo để bắt đầu.</Empty>:<div className="allocation-body"><div className="pie-wrap"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={180}><PieChart><Pie data={values.map(([name,v])=>({name,value:Number(v)}))} dataKey="value" innerRadius="62%" outerRadius="90%" paddingAngle={2} isAnimationActive={false}>{values.map(v=><Cell key={v[0]} fill={v[2]}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer></div><ul>{values.map(([name,v,color])=><li key={name}><i className="dot" style={{background:color}}/>{name}<b>{number(Number(v)*100/Number(s.total_assets))}%</b></li>)}</ul></div>}

export function LivePriceChart({points}:{points:Row[]}) {return <div className="actual-chart"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={180}><AreaChart data={points}><CartesianGrid vertical={false} stroke="#e4edf5"/><XAxis dataKey="date" tick={{fontSize:10}} minTickGap={40}/><YAxis domain={['auto','auto']} tick={{fontSize:10}} width={65}/><Tooltip formatter={v=>number(v)+' USDT'}/><Area name="Giá đóng cửa" dataKey="close" stroke="#087cf0" fill="#d8ecff"/></AreaChart></ResponsiveContainer></div>;}
